apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
  - name: opa-policy
    namespace: workshop
    files:
    - policy.rego
generatorOptions:
  disableNameSuffixHash: true