apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: productapp-gateway-tls
  namespace: workshop
spec:
  # The selector matches the ingress gateway pod labels.
  # If you installed Istio using Helm following the standard documentation, this would be "istio=ingress"
  selector:
    istio: ingressgateway-tls # use istio default controller
  servers:
  - port:
      number: 443
      name: https
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: istio-tls-credential # must be the same as secret
    hosts:
    - "*"