apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: frontend
  namespace: workshop
spec:
  host: frontend.workshop.svc.cluster.local
  subsets:
  - name: v1
    labels:
      version: v1