apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: productcatalog
  namespace: workshop
spec:
  host: productcatalog.workshop.svc.cluster.local
  subsets:
  - name: v1
    labels:
      version: v1