apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: productcatalog
  namespace: workshop
spec:
  hosts:
  - productcatalog
  http:
  - route:
    - destination:
        host: productcatalog            
        subset: v1