apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: catalogdetail
spec:
  hosts:
  - catalogdetail
  http:
  - fault:
      delay:
        percentage:
          value: 100
        fixedDelay: 600s
    route:
    - destination:
        host: catalogdetail
        subset: v2
