apiVersion: v1
kind: ConfigMap
metadata: 
  name: ratelimit-config
  namespace: workshop
data: 
  config.yaml: |
    domain: prodcatalog-ratelimit
    descriptors: 
      - key: PATH
        value: "/"
        rate_limit:
          unit: minute
          requests_per_unit: 5
      - key: PATH
        rate_limit: 
          unit: minute
          requests_per_unit: 100
