apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: productapp-mtls
  namespace: workshop
spec:
  hosts:
  - "*"
  gateways:
  - productapp-gateway-mtls
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: frontend
        port:
          number: 9000