apiVersion: v1
kind: Secret
metadata:
  annotations:
    networking.istio.io/cluster: {{ .Values.clusterName }}
  labels:
    istio/multiCluster: "true"
  name: istio-remote-secret-{{ .Values.clusterName }}
  namespace: istio-system
stringData:
  {{ .Values.clusterName }}: |
    apiVersion: v1
    clusters:
    - cluster:
        certificate-authority-data: {{ .Values.certificateAuthorityData }} 
        server: {{ .Values.server }}
      name: {{ .Values.clusterName }}
    contexts:
    - context:
        cluster: {{ .Values.clusterName }}
        user: {{ .Values.clusterName }}
      name: {{ .Values.clusterName }}
    current-context: {{ .Values.clusterName }}
    kind: Config
    preferences: {}
    users:
    - name: {{ .Values.clusterName }}
      user:
        token: {{ .Values.token }}
